# Generated by Django 5.0.1 on 2024-02-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='password',
            field=models.CharField(default=12345, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
