# Generated by Django 5.0.1 on 2024-02-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_username_lecturer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='USERNAME',
            new_name='username',
        ),
    ]
